server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/auth/**, /admin/**, /usuarios/**
        - id: material-service
          uri: lb://material-service
          predicates:
            - Path=/materiales/**, /tipo-materiales/**
        - id: almacen-service
          uri: lb://almacen-service
          predicates:
            - Path=/almacenes/**, /almacen-material/**, /movimientos/**

# Configuraci√≥n de Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # http://discovery-server:8761/eureka
    fetch-registry: true

jwt:
  secret: "586E3272357538782F413F4428472B4B6250655368566B597033733676397924"