spring:
  application:
    name: almacen-service
  datasource:
    url: jdbc:mysql://localhost:3306/bugatti_almacen_bd
    username: root
    password: Alons08
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8088

usuario-service:
  url: http://localhost:8081
material-service:
  url: http://localhost:8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "586E3272357538782F413F4428472B4B6250655368566B597033733676397924"
